init python:
    tutorial_questions = [
        ("Who is the founder of JASMS or Jose Abad Santos Memorial School?", "Doreen Barber Gamboa", "Jose Abad Santos", "Francisca Tirona Benitez", "Priscilla Abaya", "Doreen Barber Gamboa"),
        ("When was JASMS establish?", "1933", "1944", "1955", "1966", "1933"),
        ("When was PWU or Philippine Women's University establish?", "1919", "1920", "1921", "1922", "1919"),
        ("_______ is the third planet in the solar system?", "Mars", "Venus", "Earth", "Mercury", "Earth"),
        ("What is the largest bone in the body?", "Femur", "Spine", "Tibia", "Skull", "Femur"),
        ("What is the capital of France?", "London", "Paris", "Berlin", "Madrid", "Paris"),
        ("What is the largest ocean in the world?", "Atlantic", "Indian", "Pacific", "Arctic", "Pacific"),
        ("What is the largest planet in the solar system?", "Jupiter", "Saturn", "Neptune", "Uranus", "Jupiter"),
        ("What is the largest mammal in the world?", "Elephant", "Blue Whale", "Giraffe", "Hippopotamus", "Blue Whale"),
        ("What is the largest desert in the world?", "Sahara", "Arabian", "Gobi", "Kalahari", "Sahara"),
        ("What is the largest country in the world?", "Canada", "China", "Russia", "USA", "Russia"),
        ("What is the largest mountain in the world?", "Mount Everest", "K2", "Kangchenjunga", "Lhotse", "Mount Everest"),
        ("What is the largest lake in the world?", "Caspian Sea", "Lake Superior", "Lake Victoria", "Lake Michigan", "Caspian Sea"),
        ("What is the chemical symbol for water?", "H2O", "CO2", "NaCl", "O2", "H2O"),
        ("Who wrote 'To Kill a Mockingbird'?", "Harper Lee", "Mark Twain", "F. Scott Fitzgerald", "John Steinbeck", "Harper Lee"),
        ("What year did the Titanic sink?", "1912", "1907", "1921", "1915", "1912"),
        ("What is the capital of Japan?", "Kyoto", "Yokohama", "Tokyo", "Hiroshima", "Tokyo"),
        ("What is the formula for the area of a rectangle?", "Length x Width", "2 x (Length + Width)", "Length + Width", "Length^2 + Width^2", "Length x Width"),
        ("Who discovered penicillin?", "Marie Curie", "Alexander Fleming", "Isaac Newton", "Albert Einstein", "Alexander Fleming"),
        ("Which planet is known as the 'Red Planet'?", "Mars", "Venus", "Mercury", "Jupiter", "Mars"),
    ]

    questions_easy = [
        ("Who is known as the 'Father of Modern Physics'?", "Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla", "Albert Einstein"),
        ("What is the chemical symbol for iron?", "Ir", "Fe", "In", "Io", "Fe"),
        ("Who wrote 'Romeo and Juliet'?", "William Shakespeare", "Jane Austen", "Charles Dickens", "Mark Twain", "William Shakespeare"),
        ("What is the largest organ in the human body?", "Heart", "Liver", "Brain", "Skin", "Skin"),
        ("In which year did the Berlin Wall fall?", "1989", "1979", "1999", "1969", "1989"),
        ("Who invented the telephone?", "Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi", "Alexander Graham Bell"),
        ("What is the chemical symbol for sodium?", "Na", "So", "Ne", "Ni", "Na"),
        ("Who was the first woman to win a Nobel Prize?", "Marie Curie", "Rosalind Franklin", "Ada Lovelace", "Emmy Noether", "Marie Curie"),
        ("What is the capital of Brazil?", "Rio de Janeiro", "São Paulo", "Brasília", "Salvador", "Brasília"),
        ("Who discovered the theory of relativity?", "Isaac Newton", "Albert Einstein", "Galileo Galilei", "Stephen Hawking", "Albert Einstein"),
        ("What is the chemical symbol for oxygen?", "O", "O2", "CO2", "H2O", "O"),
        ("Who painted 'Starry Night'?", "Pablo Picasso", "Vincent van Gogh", "Leonardo da Vinci", "Claude Monet", "Vincent van Gogh"),
        ("In what year did the United States declare independence?", "1776", "1789", "1801", "1754", "1776"),
        ("What is the boiling point of water in Celsius?", "100°C", "0°C", "50°C", "-100°C", "100°C"),
        ("Who wrote 'Pride and Prejudice'?", "Jane Austen", "Emily Brontë", "Charlotte Brontë", "Charles Dickens", "Jane Austen"),
        ("What is the chemical symbol for silver?", "S", "Si", "Ag", "Au", "Ag"),
        ("What is the smallest country in the world?", "Vatican City", "Monaco", "Nauru", "Tuvalu", "Vatican City"),
        ("Who developed the theory of evolution by natural selection?", "Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Alfred Russel Wallace", "Charles Darwin"),
        ("What is the longest river in the world?", "Nile", "Amazon", "Yangtze", "Mississippi", "Amazon"),
        ("Who painted 'The Persistence of Memory'?", "Pablo Picasso", "Salvador Dalí", "Vincent van Gogh", "Leonardo da Vinci", "Salvador Dalí"),
        ("What is the chemical symbol for carbon?", "Ca", "C", "Co", "Cu", "C"),
        ("Who wrote '1984'?", "George Orwell", "Ray Bradbury", "Aldous Huxley", "J.R.R. Tolkien", "George Orwell"),
        ("In what year did World War II end?", "1945", "1939", "1950", "1940", "1945"),
        ("What is the formula for the circumference of a circle?", "2πr", "πr^2", "πd", "πr", "2πr"),
        ("Who composed 'The Four Seasons'?", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Antonio Vivaldi", "Antonio Vivaldi"),
        ("What is the chemical symbol for potassium?", "Pt", "P", "Po", "K", "K"),
        ("What is the highest mountain in North America?", "Denali", "Mount Rainier", "Mount St. Helens", "Mount Whitney", "Denali"),
        ("Who discovered the laws of motion?", "Isaac Newton", "Albert Einstein", "Galileo Galilei", "Stephen Hawking", "Isaac Newton"),
        ("What is the capital of South Korea?", "Seoul", "Busan", "Incheon", "Daegu", "Seoul"),
        ("Who is the creator of the 'Harry Potter' book series?", "J.K. Rowling", "Stephen King", "George R.R. Martin", "J.R.R. Tolkien", "J.K. Rowling")
    ]

    questions_normal = [
        ("Which actor portrays Iron Man in the Marvel Cinematic Universe?", "Chris Hemsworth", "Chris Evans", "Robert Downey Jr.", "Mark Ruffalo", "Robert Downey Jr."),
        ("What is the name of the lead character in the TV show 'Breaking Bad'?", "Jesse Pinkman", "Walter White", "Saul Goodman", "Skyler White", "Walter White"),
        ("Who is known as the 'King of Pop'?", "Michael Jackson", "Prince", "Elvis Presley", "David Bowie", "Michael Jackson"),
        ("'Witness the stars shatter before you. Survive or be destroyed, there is no other choice'. What game is this quote came from?", "Honkai Star Rail", "Honkai Impact 3rd", "Honkai Gakuen", "Honkai Genshin 4th", "Honkai Star Rail"),
        ("Which band released the album 'Abbey Road'?", "The Beatles", "Led Zeppelin", "The Rolling Stones", "Pink Floyd", "The Beatles"),
        ("In which movie did Leonardo DiCaprio famously say, 'I'm the king of the world'?", "Inception", "Titanic", "The Wolf of Wall Street", "The Great Gatsby", "Titanic"),
        ("Who is the director of the film 'Pulp Fiction'?", "Steven Spielberg", "Quentin Tarantino", "Christopher Nolan", "Martin Scorsese", "Quentin Tarantino"),
        ("What is the name of the fictional city where Batman operates?", "Gotham City", "Metropolis", "Central City", "Star City", "Gotham City"),
        ("Which TV show features a group of friends living in New York City?", "Friends", "The Office", "How I Met Your Mother", "Seinfeld", "Friends"),
        ("Who won the first season of 'American Idol'?", "Kelly Clarkson", "Carrie Underwood", "Adam Lambert", "Jennifer Hudson", "Kelly Clarkson"),
        ("Which of Newton's Laws of Motion states that for every action, there is an equal and opposite reaction?", "The 1st Law", "The 2nd Law", "The 3rd Law", "The 4th Law", "The 3rd Law"),
        ("Ano ang national tree ng Pilipinas?", "Niyog", "Narra", "Banaba", "Katmon", "Narra"),
        ("What is the most commonly used word in the English language?", "What", "The", "An", "I", "The"),
        ("What is the most popular sport in Brazil?", "Football", "Baseball", "Volleyball", "Basketball", "Football"),
        ("Only one letter doesn't appear in any US state name. What is it?", "X", "Q", "Z", "J", "Q"),
        ("What is the current official name of Big Ben?", "The Great Bell", "Elizabeth Tower", "Clock Tower", "Westminster Tower", "Elizabeth Tower"),
        ("What is the fear of the color yellow?", "Erythrophobia", "Prasinophobia", "Rhodophobia", "Xanthophobia", "Xanthophobia"),
        ("How many wings do fleas have?", "4", "6", "0", "2", "0"),
        ("Which of the waterfalls that make up Niagara Falls is the largest?", "American Falls", "Horseshoe Falls", "Bridal Veil Falls", "Ontario Falls", "Horseshoe Falls"),
        ("Where is the venus flytrap native to?", "South America", "West Siberia", "North and South Carolina", "Australia", "North and South Carolina"),
        ("There's an apartment building downtown with four floors. The higher the floor, the more people live there. Which floor does the elevator go to most often?", "The first floor", "The second floor", "The third floor", "The fourth floor", "The first floor"),
        ("What is the tube at the little ends of the shoelace called?", "Knot", "Aglet", "Hemp", "Jute", "Aglet"),
        ("What is the main function of chlorophyll in photosynthesis?", "Absorb oxygen", "Convert carbon dioxide into glucose", "Absorb light energy", "Produce water", "Absorb light energy"),
        ("Which of the following is an example of a renewable energy source?", "Coal", "Natural gas", "Solar power", "Oil", "Solar power"),
        ("What is the primary function of vaccines?", "To cure diseases", "To prevent diseases", "To treat symptoms of diseases", "To enhance immunity to diseases", "To prevent diseases"),
        ("What is the process by which plants use light energy to produce glucose and oxygen?", "Respiration", "Fermentation", "Photosynthesis", "Transpiration", "Photosynthesis"),
        ("Who was the last emperor of the Byzantine Empire?", "Constantine XI", "Justinian I", "Heraclius", "Alexios I Komnenos", "Constantine XI"),
        ("Who directed the movie 'Inception'?", "Christopher Nolan", "Quentin Tarantino", "Steven Spielberg", "Martin Scorsese", "Christopher Nolan"),
        ("Who is known as the 'Queen of Pop'?", "Madonna", "Beyonce", "Lady Gaga", "Rihanna", "Madonna"),
        ("Which movie won the Academy Award for Best Picture in 2010?", "Inception", "The King's Speech", "The Social Network", "Black Swan", "The King's Speech"),
        ("What is the name of the main character in the TV series 'Breaking Bad'?", "Walter White", "Jesse Pinkman", "Saul Goodman", "Skyler White", "Walter White"),
        ("What is the value of 86percent of 200?", "174", "172", "177", "179", "172"),
        ("Sino ang kinikilalang 'Queen of All Media' sa Pilipinas?", "Kris Aquino", "Korina Sanchez", "Toni Gonzaga", "Boy Abunda", "Kris Aquino"),
        ("What is the sum of the interior angles of a hexagon?", "900 degrees", "450 degrees", "540 degrees", "720 degrees", "720 degrees"),
        ("Ano ang tawag sa pinakapopular na pagkain sa Pilipinas, lalo na sa almusal?", "Sinigang", "Adobo", "Tinola", "Tapsilog", "Tapsilog"),
        ("Sino ang may-akda ng 'Noli Me Tangere' at 'El Filibusterismo'?", "Andres Bonifacio", "Jose Rizal", "Emilio Aguinaldo", "Apolinario Mabini", "Jose Rizal"),
        ("Ano ang tawag sa pinakamalaking lungsod sa Pilipinas?", "Quezon City", "Davao City", "Manila", "Cebu City", "Quezon City"),
        ("What is 8x12?", "96", "68", "108", "42", "96"),
        ("What is the value of 3x5+8?", "15", "23", "17", "40", "23"),
        ("When did the first Mario game release?", "1992", "1983", "2001", "1972", "1983"),
        ("What is the name of Nintendo's handheld gaming console that succeeded the Game Boy Advance?", "Nintendo DS", "Nintendo 3DS", "Game Boy Color", "Game Boy Advance SP", "Nintendo DS"),
        ("In the 'Super Smash Bros.' series, who is the creator of the game?", "Shigeru Miyamoto", "Satoru Iwata", "Masahiro Sakurai", "Satoshi Tajiri", "Masahiro Sakurai"),
        ("Ano ang tawag sa pinakamalaking bulkang aktibo sa Pilipinas?", "Taal Volcano", "Mount Mayon", "Mount Pinatubo", "Mount Apo", "Mount Mayon"),
        ("What causes tides on Earth?", "Gravitational pull of the Moon", "Gravitational pull of the Sun", "Earth's rotation", "Earth's magnetic field", "Gravitational pull of the Moon"),
        ("What is the hardest natural substance on Earth?", "Iron", "Diamond", "Quartz", "Gold", "Diamond"),
        ("What is the process by which a liquid becomes a gas at the surface of the liquid?", "Evaporation", "Condensation", "Sublimation", "Freezing", "Evaporation"),
        ("What is the largest ocean on Earth?", "Atlantic Ocean", "Indian Ocean", "Southern Ocean", "Pacific Ocean", "Pacific Ocean"),
        ("What is the capital of Canada?", "Vancouver", "Montreal", "Ottawa", "Toronto", "Ottawa"),
        ("What is the largest city in the United States by population?", "Los Angeles", "Chicago", "New York City", "Houston", "New York City"),
        ("What is the longest river in Europe?", "Volga", "Rhine", "Danube", "Thames", "Volga")
    ]

    questions_normal2 = [
        ("Aling pagdiriwang ng Pilipinas ang kilala bilang 'Festival of Festivals'?", "Sinulog Festival", "Ati-Atihan Festival", "Dinagyang Festival", "Pahiyas Festival", "Ati-Atihan Festival"),
        ("Ano ang pangalan ng pambansang bulaklak ng pilipinas?", "Sampaguita", "Ylang-Ylang", "Dama de Noche", "Waling-Waling", "Sampaguita"),
        ("Ano ang chemical formula para sa tubig?", "H2O", "CO2", "O2", "H2SO4", "H2O"),
        ("What does VPN stand for?", "Virtual Personal Network", "Virtual Private Network", "Verified Public Network", "Visual Processing Node", "Virtual Private Network"),
        ("Which of the following is a type of malware that encrypts files and demands payment for their release?", "Virus", "Worm", "Trojan horse", "Ransomware", "Ransomware"),
        ("Who led the Philippine troops during the Battle of Bataan in World War II?", "Emilio Aguinaldo", "Manuel L. Quezon", "Douglas MacArthur", "Ramon Magsaysay", "Douglas MacArthur"),
        ("What event marked the beginning of the Philippine Revolution against Spanish rule?", "The Cry of Pugad Lawin", "The Battle of Mactan", "The Execution of Gomburza", "The Battle of Manila Bay", "The Cry of Pugad Lawin"),
        ("Which of the following is a storage device?", "Keyboard", "Mouse", "Hard Disk Drive (HDD)", "Monitor", "Hard Disk Drive (HDD)"),
        ("Ano ang tradisyunal na sayaw ng mga Pilipino na madalas itanghal tuwing may pagdiriwang?", "Tinikling", "Singkil", "Pandanggo sa Ilaw", "Maglalatik", "Tinikling"),
        ("What is the value of 3x5+2?", "15", "17", "19", "20", "17"),
        ("What is the purpose of a firewall?", "To protect against viruses", "To filter network traffic", "To create digital artwork", "To compose music", "To filter network traffic"),
        ("What does URL stand for?", "Uniform Resource Locator", "Universal Resource Locator", "Uniform Reference Locator", "Universal Reference Locator", "Uniform Resource Locator"),
        ("What is the tallest mountain in the Philippines?", "Mount Mayon", "Mount Pulag", "Mount Apo", "Mount Pinatubo", "Mount Apo"),
        ("Aling pangkat etniko ang kilala sa kanilang husay sa paghahabi ng mga tradisyunal na tela tulad ng inabel?", "Igorot", "T'boli", "Ifugao", "Ilokano", "Ilokano"),
        ("Ano ang tawag sa tradisyunal na sining ng martial Filipino?", "Pencak Silat", "Krav Maga", "Eskrima", "Muay Thai", "Eskrima"),
        ("What literary device is used when a statement's meaning is different from its literal meaning?", "Irony", "Metaphor", "Simile", "Hyperbole", "Irony"),
        ("Who wrote the poem 'The Waste Land'?", "T.S. Eliot", "Robert Frost", "Walt Whitman", "Langston Hughes", "T.S. Eliot"),
        ("Which of the following is a type of volatile memory?", "ROM", "RAM", "HDD", "SSD", "RAM"),
        ("What is the square root of 81?", "7", "8", "9", "10", "9"),
        ("What is the nickname given to the Philippines due to its frequent typhoons?", "Pearl of the Orient", "Land of the Rising Sun", "Archipelago of the Pacific", "Typhoon Alley", "Typhoon Alley"),
        ("Who is the author of 'The Catcher in the Rye'?", "J.D. Salinger", "Ernest Hemingway", "F. Scott Fitzgerald", "Mark Twain", "J.D. Salinger"),
        ("Which of the following is NOT a health-related component of physical fitness?", "Body composition", "Muscular strength", "Reaction time", "Cardiovascular endurance", "Reaction time"),
        ("Which of the following is a consequence of a sedentary lifestyle?", "Improved cardiovascular health", "Increased risk of obesity", "Enhanced flexibility", "Better sleep quality", "Increased risk of obesity"),
        ("What is the value of 58 as a percentage?", "37.5%", "62.5%", "125%", "625%", "62.5%"),
        ("What is the main function of the kidneys in the human body?", "Regulation of blood pressure", "Production of red blood cells", "Filtration of blood and waste removal", "Digestion of food", "Filtration of blood and waste removal"),
        ("Saan matatagpuan ang Taal Volcano?", "Batangas", "Albay", "Bataan", "Quezon", "Batangas"),
        ("Which of the following is a primary function of an antivirus software?", "Creating documents", "Protecting against malware", "Playing videos", "Editing images", "Protecting against malware"),
        ("Which of the following is an example of a web browser?", "Microsoft Word", "Google Chrome", "Adobe Photoshop", "VLC Media Player", "Google Chrome"),
        ("Which of the following is a dynamic stretching exercise?", "Toe touches", "Sit and reach", "Arm circles", "Holding a yoga pose", "Arm circles"),
        ("What is 9 + 10?", "21", "19", "910", "1", "19"),
        ("What is the term for the use of humor, irony, exaggeration, or ridicule to expose and criticize people's stupidity or vices?", "Satire", "Parody", "Irony", "Sarcasm", "Satire"),
        ("Which of the following is not a component of blood?", "Plasma", "Platelets", "Hormones", "Red blood cells", "Hormones"),
        ("What literary device is used in the phrase 'time flies'?", "Metaphor", "Simile", "Personification", "Hyperbole", "Personification"),
        ("What is the name of the traditional dance of Argentina?", "Samba", "Tango", "Flamenco", "Capoeira", "Tango"),
        ("What is the name of the traditional dance of Hawaii?", "Hula", "Flamenco", "Capoeira", "Bhangra", "Hula"),
        ("Which of the following is a programming language commonly used for data analysis and machine learning?", "Java", "Python", "C++", "Ruby", "Python"),
        ("What is the purpose of a power supply unit (PSU)?", "To display images on the monitor", "To provide power to the computer components", "To scan documents", "To connect to the internet", "To provide power to the computer components"),
        ("Solve for x in the equation 2^x = 16.", "2", "3", "4", "5", "4"),
        ("Solve for x in the equation 3(x-2)=12.", "2", "4", "6", "8", "6"),
        ("Ano ang tawag sa Filipino para sa mga ninong at ninang?", "Ninong at Ninang", "Tito at Tita", "Kuya at Ate", "Lolo at Lola", "Ninong at Ninang"),
        ("What is the main theme of the novel 'To Kill a Mockingbird'?", "Love and betrayal", "Friendship and loyalty", "Racial injustice and moral growth", "Revenge and forgiveness", "Racial injustice and moral growth"),
        ("Which of the following activities primarily improves balance and coordination?", "Running", "Cycling", "Yoga", "Weightlifting", "Yoga"),
        ("Which of the following is an example of a moderate-intensity physical activity?", "Walking briskly", "Sprinting", "Jumping rope", "Playing basketball", "Walking briskly"),
        ("Which of the following exercises primarily targets the abdominal muscles?", "Push-ups", "Sit-ups", "Lunges", "Squats", "Sit-ups"),
        ("What does CPU stand for?", "Central Processing Unit", "Computer Processing Unit", "Central Power Unit", "Control Processing Unit", "Central Processing Unit"),
        ("Ano ang tawag sa lihim na samahan na itinatag ni Andres Bonifacio?", "Katipunan", "Magdiwang", "KKK", "Liga Filipina", "Katipunan"),
        ("Ano ang tawag sa anyo ng panitikan na naglalahad ng mga karanasan, pangarap, at damdamin ng may-akda?", "Awit", "Soneto", "Oda", "Tula", "Tula"),
        ("Ano ang tawag sa wika na may katutubong katangian at ginagamit ng mga tao sa isang partikular na rehiyon sa Pilipinas?", "Dayalek", "Lalawiganin", "Barok", "Etniko", "Dayalek"),
        ("Sino ang tinaguriang 'Ama ng Tulang Filipino'?", "Andres Bonifacio", "Jose Rizal", "Francisco Balagtas", "Fernando Amorsolo", "Francisco Balagtas"),
        ("Ano ang tawag sa uri ng salita na nagpapahiwatig ng kilos o galaw?", "Pang-uri", "Pandiwa", "Panghalip", "Pang-abay", "Pandiwa")
    ]

    questions_hard = [
        ("Saan itinuturing na pinakamataas na antas ng wika?", "Kolokyal", "Barok", "Pampanitikan", "Balbal", "Pampanitikan"),
        ("Anong tawag sa pagsasanib ng mga kataga mula sa iba't ibang wika?", "Kodigo", "Kombinasyon", "Kodikasyon", "Kode-switching", "Kode-switching"),
        ("Ano ang tawag sa salitang hiram mula sa Espanyol sa Filipino?", "Inglesismo", "Kastilalismo", "Hispanismo", "Pilipinismo", "Hispanismo"),
        ("Ano ang tawag sa mga tula na ginagamit sa kasalukuyang panahon?", "Epiko", "Korido", "Modernong Tula", "Awit", "Modernong Tula"),
        ("Ano ang tawag sa anyo ng panitikan na naglalarawan ng pang-araw-araw na buhay o karanasan ng mga tao?", "Maikling Kuwento", "Nobela", "Sanaysay", "Balagtasan", "Sanaysay"),
        ("What is the standard height of a volleyball net for men's competition?", "2.40 meters (7 feet 10 inches)", "2.43 meters (8 feet)", "2.55 meters (8 feet 4 inches)", "2.60 meters (8 feet 6 inches)", "2.43 meters (8 feet)"),
        ("What is the term for a violation that occurs when a player steps on or over the center line during play?", "Carry", "Foot fault", "Net violation", "Rotation error", "Foot fault"),
        ("What is the term for a serve that results in a point without the receiving team touching the ball?", "Fault", "Ace", "Carry", "Dig", "Ace"),
        ("What is the area of a rectangle with length 6 units and width 4 units?", "12 square units", "16 square units", "20 square units", "24 square units", "24 square units"),
        ("What is 2 to the power of 5?", "8", "16", "32", "64", "32"),
        ("What is 25% written as a fraction?", "1/2", "1/3", "1/4", "1/5", "1/4"),
        ("What is the area of a square with side length 7 units?", "28 square units", "35 square units", "42 square units", "49 square units", "49 square units"),
        ("Which movie won the Academy Award for Best Picture in 1994?", "Titanic", "Forrest Gump", "Schindler's List", "The Silence of the Lambs", "Forrest Gump"),
        ("Which movie features the famous line: 'Here's looking at you, kid'?", "Casablanca", "Gone with the Wind", "Citizen Kane", "The Maltese Falcon", "Casablanca"),
        ("Which movie features the iconic line: 'You can't handle the truth!'?", "A Few Good Men", "Platoon", "Apocalypse Now", "Full Metal Jacket", "A Few Good Men"),
        ("What is the meaning of life?", "To seek happiness and fulfillment", "To fulfill one's duty or purpose", "To find meaning in one's existence", "There is no single meaning; it's subjective", "There is no single meaning; it's subjective"),
        ("Who directed the 1994 film 'Pulp Fiction'?", "Quentin Tarantino", "Coen Brothers", "Wes Anderson", "Paul Thomas Anderson", "Quentin Tarantino"),
        ("What is a turnover in basketball?", "A type of dribbling technique", "Passing the ball to the opposing team", "Scoring a point from outside the three-point line", "Losing possession of the ball to the opposing team due to a violation", "Losing possession of the ball to the opposing team due to a violation"),
        ("How long is a standard NBA basketball game?", "30 minutes", "40 minutes", "48 minutes", "60 minutes", "48 minutes"),
        ("What is a rebound in basketball?", "When the ball bounces off the rim or backboard after a missed shot", "A type of shot taken close to the basket", "Passing the ball to a teammate", "Shooting the ball from the half-court line", "When the ball bounces off the rim or backboard after a missed shot"),
        ("Sino ang pumili at nag-akda ng liriko ng Pambansang Awit ng Pilipinas?", "Julian Felipe", "Jose Palma", "Andres Bonifacio", "Emilio Aguinaldo", "Jose Palma"),
        ("Alin sa mga sumusunod ang hindi katangian ng mga alkali metals?", "Madaling masunog", "Malambot at manipis", "Malambot at manipis", "Marunong magtunaw sa tubig", "Marunong magtunaw sa tubig"),
        ("Anong uri ng enerhiya ang nakukuha mula sa daloy ng tubig tulad ng sa mga dam?", "Solar energy", "Wind energy", "Hydroelectric energy", "Geothermal energy", "Hydroelectric energy"),
        ("Aling dalawang planeta sa ating solar system ang hindi mayroong natural na satellite o moon?", "Mercury at Venus", "Earth at Mars", "Jupiter at Saturn", "Uranus at Neptune", "Mercury at Venus"),
        ("What is the correct comparative form of the adjective 'good'?", "Better", "Gooder", "Goodest", "More good", "Better"),
        ("Which punctuation mark is used to indicate possession?", "Apostrophe (' )", "Comma (,)", "Colon (:)", "Semicolon (;)", "Apostrophe (' )"),
        ("Who wrote the poem 'The Raven'?", "Robert Frost", "Emily Dickinson", "Edgar Allan Poe", "Walt Whitman", "Edgar Allan Poe"),
        ("What literary device is used in the phrase 'time flies'?", "Simile", "Metaphor", "Personification", "Hyperbole", "Metaphor"),
        ("Which programming language is commonly used for building websites?", "Python", "Java", "HTML", "C++", "HTML"),
        ("Which of the following is a type of malware that spreads by replicating itself and infecting other files?", "Virus", "Spyware", "Trojan", "Worm", "Worm"),
        ("What is the purpose of a router in a computer network?", "To connect devices within a LAN", "To connect devices within a WAN", "To connect different networks together", "All of the above", "All of the above"),
        ("What is the purpose of an IP address?", "To identify a device on a network", "To store files", "To create folders", "To format a hard drive", "To identify a device on a network"),
        ("Which of the following is an example of a secondary source?", "Interview transcript", "Research article reporting experimental results", "Encyclopedia entry", "Original government document", "Encyclopedia entry"),
        ("What does the acronym 'AP' stand for in journalism?", "Advanced Publishing", "Associated Press", "Authoritative Publication", "Accredited Press", "Associated Press"),
        ("What is the purpose of a media literacy curriculum?", "To promote critical thinking skills", "To teach media production techniques", "To encourage blind trust in media sources", "To promote censorship", "To promote critical thinking skills"),
        ("Which of the following is an example of a primary source?", "Textbook", "Diary", "News article", "Encyclopedia", "Diary"),
        ("What does the acronym 'SEO' stand for in the context of online content?", "Search Engine Optimization", "Social Engagement Outreach", "Site Enhancement Operation", "Search Engine Operation", "Search Engine Optimization"),
        ("What is the purpose of fact-checking in the media?", "To verify the accuracy of information", "To promote fake news", "To manipulate public opinion", "To spread rumors", "To verify the accuracy of information"),
        ("If a tree falls in a forest and no one is around to hear it, does it make a sound?", "Yes, because sound is a physical phenomenon", "No, because sound requires an observer to perceive it", "Maybe, because the definition of ‘sound’ varies", "It depends on the tree's intention", "Yes, because sound is a physical phenomenon"),
        ("What is the name of the game that popularized the battle royale genre?", "Call of Duty: Warzone", "PlayerUnknown's Battlegrounds", "Fortnite", "Apex Legends", "PlayerUnknown's Battlegrounds"),
        ("What is the result of 15+(3x4)/2?", "21", "18", "24", "12", "18"),
        ("What is the area of a rectangle with length 8 units and width 5 units?", "13 square units", "40 square units", "45 square units", "20 square units", "40 square units"),
        ("If x+7=15, what is the value of x?", "8", "22", "7", "15", "8"),
        ("If a box contains 24 candies and you distribute them equally among 6 friends, how many candies will each friend get?", "6", "4", "5", "8", "4"),
        ("What is the next number in the sequence: 2, 5, 10, 17, ...?", "25", "21", "26", "27", "26"),
        ("If a clock shows 3:45 PM, how many degrees does the minute hand move if it moves to 9:15 PM?", "180 degrees", "270 degrees", "360 degrees", "90 degrees", "270 degrees"),
        ("What is the perimeter of a square with each side measuring 6 units?", "12 units", "18 units", "24 units", "36 units", "24 units"),
        ("If a pizza has 8 slices and you eat 3 slices, what fraction of the pizza remains?", "3/8", "5/8", "1/2", "3/5", "5/8"),
        ("What is the value of 5^3/25+4?", "24", "15", "9", "29", "9"),
        ("Who is the current principal of JASMS QC as of 2024?", "Diane Cynthia G. Gutierrez", "Juan Dela Cruz", "Dr. Roberto Cruz", "Maria Santos", "Diane Cynthia G. Gutierrez")
    ]

    questions_hard2 = [
        ("What is 102 x 27 - 430 + 1027?", "2,760", "3,225", "3351", "345", "3351"),
        ("What is the solution to the equation 2x + 3 = 11?", "x = 4", "x = 5", "x = 6", "x = 7", "x = 5"),
        ("What is the square root of 144?", "11", "12", "13", "14", "12"),
        ("If f(x) = 3x^2 - 2x + 5 and g(x) = x + 1, what is f(g(2))?", "17", "21", "26", "29", "26"),
        ("What is the primary function of mitochondria in the cell?", "Protein synthesis", "Energy production", "Waste elimination", "Cell division", "Energy production"),
        ("What is the solution to the equation 2^x = 16?", "x = 2", "x = 3", "x =4", "x = 5", "x = 4"),
        ("What is the value of 3^4?", "9", "12", "27", "81", "81"),
        ("Solve the inequality 4x - 3 > 9.", "x >3", "x < 3", "x > 6", "x < 6", "x > 6"),
        ("If a rectangle has a length of 10 meters and a width of 5 meters, what is its area?", "25 square meter", "35 square meters", "45 square meters", "50 square meters", "50 square meters"),
        ("A car travels at a constant speed of 60 miles per hour. How far will it travel in 3 hours?", "120 miles", "150 miles", "180 miles", "210 miles", "180 miles"),
        ("Burning natural gas in your furnace is an example of what type of change?", "physical change", "electrical change", "chemical change", "atomic change", "chemical change"),
        ("Ito ay isang katangian ng bagay na hindi nasusukat sa pamamagitan ng pagkalkula ng dalawa o higit pang pisikal na bilang.", "weight", "mass", "density", "volume", "mass"),
        ("Ito ang tawag sa kabuuang kinetic energy ng lahat ng molecule ng isang bagay.", "temperatura", "init", "calorie", "grabidad", "init"),
        ("A general characteristic of species is that members _______.", "have the same adaptation and diet", "all live in the same location", "cannot produce hybrids with other species", "can interbreed and produce a fertile offspring", "can interbreed and produce a fertile offspring"),
        ("An example of compound is _________.", "mercury", "salt", "bronze", "oxygen", "salt"),
        ("What is the term for the amount of heat required to raise the temperature of one gram of a substance by one degree Celsius?", "Heat capacity", "Specific heat", "Latent heat", "Enthalpy", "Specific heat"), 
        ("Which of the following is a halogen", "Fluorine (F)", "Sodium (Na)", "Potassium (K)", "Calcium (Ca)", "Fluorine (F)"),
        ("What is the term for the number of protons in the nucleus of an atom?", "Atomic mass", "Atomic number", "Mass number", "Isotope number", "Atomic number"),
        ("What is the chemical symbol for gold?", "Au", "Ag", "Pt", "Hg"),
        ("Which of the following is non-metal", "Magnesium (Mg)", "Oxygen (O)", "Copper (Cu)", "Sodium (Na)", "Oxygen (O)"),
        ("What is the correct definition of a protagonist in literature?", "The sequence of events in a story", "The central idea or message", "The main character who drives the plot forward", "The time and place in which a story takes place", "The main character who drives the plot forward"),
        ("What is the main purpose of an introduction paragraph in an essay", "To provide evidence", "To summarize the main points", "To engage the reader and introduce the topic", "To present the main argument", "To engage the reader and introduce the topic"),
        ("What is the correct definition of a theme in literature?", "The sequence of events in a story", "The central idea or message", "The time and place in which a story takes place", "The main character in a story", "The central idea or message"),
        ("What is the main purpose of a thesis statement in an essay?", "To summarize the main points", "To introduce the topic", "To provide evidence", "To present the main argument", "To present the main argument"),
        ("In the sentence 'The cat chased the mouse,' what is the object", "The", "Cat", "Chased", "Mouse", "Mouse"),
        ("Which ancient civilization is credited with the invention of the first known writing system?", "Ancient Greeks", "Sumerians", "Egyptians", "Romans", "Sumerians"),
        ("What is the term for a play that ends in catastrophe for the main character?", "Comedy", "Tragedy", "Farce", "Satire", "Tragedy"),
        ("What is the term for a long poem that tells the story of a hero's adventures?", "Sonnet", "Epic", "Ode", "Ballad", "Epic"),
        ("What is the term for a word that modifies a noun?", "Verb", "Pronoun", "Adjective", "Adverb", "Adjective"),
        ("What is the term for the study of the origin and history of words?", "Syntax", "Semantics", "Etymology", "Phonetics", "Etymology"),
        ("Sinong kompositor ang sumulat ng 'The Marriage of Figaro'?", "Wolgang Amadeus Mozart", "Ludwig van Beethoven", "Johann Sebastian Bach", "Franz Schubert", "Wolfgang Amadeus Mozart"),
        ("Ano ang ibig sabihin ng idyolek?", "Isang uri ng diyalekto", "Isang pribadong wika ng isang indibidwal", "Isang opisyal na wika", "Isang sinaunang wika", "Isang pribadong wika ng isang indibidwal"),
        ("Saang rehiyon sa Pilipinas matatagpuan ang wikang Waray?", "Luzon", "Visayas", "Mindanao", "Palawan", "Visayas"),
        ("Ano ang pragmatika sa linggwistika?", "Pag-aaral ng praktikal na paggamit ng wika", "Pag-aaral ng mga patakaran ng wika", "Pag-aaral ng mga tunog ng wika", "Pag-aaral ng pagsulat", "Pag-aaral ng praktikal na paggamit ng wika"),
        ("Ano ang semantika?", "Pag-aaral ng mga tunog", "Pag-aaral ng mga kahulugan", "Pag-aaral ng mga istruktura ng pangungusap", "Pag-aaral ng mga salitang hiram", "Pag-aaral ng mga kahulugan"),
        ("Ano ang isa sa mga layunin ng globalisasyon?", "Pagpapalakas ng pagkakaiba-iba ng bawat bansa", "Pagpapababa ng mga hangganan sa pagitan ng mga bansa", "Pagpapalitan ng ideya at kalakalan sa iba't ibang bansa", "Pagpapalakas ng ugnayan sa ibang mga bansa", "Pagpapalitan ng ideya at kalakalan sa iba't ibang bansa"),
        ("Ano ang isa sa mga epekto ng globalisasyon sa sektor ng agrikultura?", "Pagpapababa ng presyo ng mga agrikultural na produkto", "Pagpapalakas ng pagsasaka sa lokal na antas", "Pagpapalawak ng merkado para sa mga loka na magsasaka", "Pagsusulong ng industriyalisasyon sa pagitan ng mga bansa"),
        ("Anong tawag sa pag-unlad ng teknolohiya at komunikasyon na nagbubukas ng mga oportunidad sa iba't ibang bansa?", "Globalisasyon", "Teknolohikal na Pag-unlad", "Cyber-Expansion", "Human Advancement"),
        ("What is the name of the orphanage that Arlecchino run", "House of Daena", "House of the Hearth", "House of Heart", "House of Fire", "House of the Hearth"),
        ("To which character does the constellation 'Mantichora' belong to?", "Dehya", "Chevruse", "Diluc", "Jean", "Dehya"),
        ("To which character does the constellation 'Monoceros Caeli' belong to?", "Ayato", "Furina", "Tartaglia", "Xingqui", "Tartaglia"),
        ("Which file format is commonly used for storing animated sequences with transparent backgrounds", "GIF", "MP4", "AVI", "MOV", "GIF"),
        ("In 3D animation, what does 'rigging' refer to?", "Adding texture to 3D models", "Creating skeletal structures for characters", "Adjusting lighting and shading", "Rendering the final animation frams", "Creating skeletal structures for characters"),
        ("What does the term 'FPS' stand for in animation?", "Frames Per Sequence", "Frames Per Second", "Full-Performance System", "Frame Positioning Speed", "Frames Per Second"),
        ("Which animation principle involves exaggerating movements to make them more expressive?", "Exaggeration", "Solid Drawing", "Secondary Action", "Timing", "Exaggeration"),
        ("Which principle of animation focuses on the idea that every action should have a clear purpose and be communicated effectively to the audience?", "Staging", "Straight ahead action and pose to pose", "Appeal", "Solid Drawing", "Staging"),
        ("Which of the following is NOT a type of animation?", "Morphing", "Pixilation", "Shading", "Flipbook animation", "Shading"),
        ("Which animation priniciple involves giving characters a sense of internal life and personality?", "Pose to Pose", "Appeal", "Exaggeration", "Secondary Action", "Appeal"),
        ("Which animation technique involves creating 2D animations by manipulating flat objects", "Cel animation", "Cut-out animation", "Rotoscoping", "Claymation", "Cut-out animation"),
        ("Which animation term refers to the process of creating a seamless transition between the end and beginning of an animation?", "Looping", "Tweening", "Easing", "Cross-fading", "Looping"),

    ]

    questions_hard3 = [
        ("Which animation technique involves creating realistic movement by recording the motions of real actors", "Rotoscoping", "Motion capture", "Stop-motion animation", "Cel animation", "Motion capture"),
        ("Who is often considered the 'Father of Modern Dance'?", "Isadora Duncan", "Martha Graham", "Gene Kelly", "Fred Astaire", "Isadora Duncan"),
        ("What dance style is characterized by its fast-paced movements and often involves partnering and lifts?", "Ballet", "Ballroom", "Breakdancing", "Jazz", "Ballroom"),
        ("Which of the following is NOT a Latin dance?", "Salsa", "Tango", "Waltz", "Cha-cha", "Waltz"),
        ("Which dance style is characterized by its graceful and flowing movements, often performed on pointe?", "Hip-hop", "Ballet", "Jazz", "Breakdancing", "Ballet"),
        ("Which dance style originated in the Middle East and involves isolating different parts of the body?", "Belly dance", "Capoeira", "Samba", "Breakdancing", "Belly dance"),
        ("Which dance style is often associated with the Roaring Twenties and the Jazz Age?", "Waltz", "Charleston", "Samba", "Flamenco", "Charleston"),
        ("What is the name of the traditional dance of Spain?", "Tango", "Charleston", "Samba", "Flamenco", "Flamenco"),
        ("Which dance style involves a series of steps and patterns danced in a line or circle formation?", "Tap dance", "Line dance", "Ballet", "Ballroom", "Line dance"),
        ("Who is often considered the 'Queen of Salsa'?", "Gloria Estefan", "Celia Cruz", "Josephine Baker", "Gregory Hines", "Celia Cruz"),
        ("Which dance style originated in the African American communities of Harlem during the 1920s?", "Salsa", "Tap dance", "Tango", "Swing", "Swing"),
        ("What subject deals with the study of human culture, its development, and artifacts?", "Anthropology", "Sociology", "Psychology", "Political Science", "Anthropology"),
        ("In which subject do students examine the principles of logic and reasoning?", "Mathematics", "Philosophy", "Psychology", "Sociology", "Philosophy"),
        ("What subject deals with the study of past events and their impact on society?", "Geography", "History", "Anthropology", "Political Science", "History"),
        ("Which art movement was characterized by vibrant colors and bold brushstrokes?", "Impressionism", "Cubism", "Surrealism", "Abstract Expressionism", "Impressionism"),
        ("Who designed the iconic 'Barcelona Chair'?", "Ludwig Mies van der Rohe", "Le Corbusier", "Alvar Aalto", "Charles and Ray Eames", "Ludwig Mies van der Rohe"),
        ("Which artist is known for her large-scale flower paintings?", "Georgia O'Keeffe", "Frida Kahlo", "Louise Bourgeois", "Yayoi Kusama", "Georgia O'Keeffe"),
        ("Which design movement emphasized simplicity, functionality, and clean lines?", "Art Nouveau", "Bauhaus", "Art Deco", "Postmodernism", "Bauhaus"),
        ("Which Renaissance artist sculpted the statue of David?", "Leonardo da Vinci", "Michelangelo", "Donatello", "Raphael", "Michelangelo"),
        ("What is the term for the practice of managing household finances effectively?", "Budgeting", "Spending spree", "Impulse buying", "Luxury shopping", "Budgeting"),
        ("What is a crucial safety measure when using electrical appliances?", "Overloading electrical outlets", "Handling appliances with wet hands", "Reading and following instructions", "Using appliances with frayed cords", "Reading and following instructions"),
        ("Which philosophical concept refers to the study of knowledge, belief and justification?", "Metaphysics", "Epistemology",  "Ethics", "Aesthetics", "Epistemology"),
        ("Who is the author of 'The Republic,' a seminal work in political philosophy?", "Aristotle", "Plato", "Socrates", "Thomas Aquinas", "Plato"),
        ("Which philosophical tradition emphasizes the importance of mindfulness and meditation?", "Stoicism", "Taoism", "Buddhism", "Confucianism", "Buddhism"),
        ("Which ancient philosopher is known for his writings on Stoicism?", "Epictetus", "Socrates", "Plato", "Aristotle", "Epictetus"),
        ("Who is known for his categorical imperative in ethical philosophy?", "Immanuel Kant", "Aristotle", "John Stuart Mill", "Jeremy Bentham", "Immanuel Kant"),
        ("What does 'cultural relativism' emphasize?", "The superiority of one culture over others", "Judging a culture based on its own standards", "Imposing one's cultural values on others", "Ignoring cultural differences", "Judging a culture based on its own standards"),
        ("What is the term for the tendency to view one's own culture as superior to others?", "Cultural relativism", "Ethnocentrism", "Multiculturalism", "Cultural diversity", "Ethnocentrism"),
        ("Which of the following is NOT a component of culture?", "Language", "Religion", "Genetics", "Values", "Genetics"),
        ("What is the term for the process by which individuals learn the norms and values of their culture?", "Cultural assimilation", "Cultural diffusion", "Cultural transmission", "Cultural adaptation", "Cultural transmission"),
        ("Which of the following is NOT a characteristic of culture?", "It is static and unchanging", "It is learned", "It is shared", "It is adaptive", "It is static and unchanging"),
        ("What is the term for the process by which cultural traits spread from one society to another?", "Cultural diffusion", "Cultural assimilation", "Cultural relativism", "Cultural transmission", "Cultural diffusion"),
        ("Which theoretical perspective focuses on how culture reflects and perpetuates social inequality?", "Conflict theory", "Functionalism", "Symbolic interactionism", "Feminist theory", "Conflict theory"),
        ("Which of the following is an example of a cultural trait?", "Language", "Genetic makeup", "Physical environment", "Biological evolution", "Language"),
        ("What is the term for the process by which individuals from one culture adopt the cultural practices of another culture?", "Cultural diffusion", "Cultural assimilation", "Cultural relativism", "Cultural transmission", "Cultural assimilation"),
        ("Which of the following is an example of material culture?", "Language", "Beliefs", "Artifacts", "Social norms", "Artifacts"),
        ("What is the primary focus of PWU JASMS's mission statement?", "Excellence in academic research", "Fostering a nurturing learning environment", "Profit maximization", "Providing corporate training solutions", "Fostering a nurturing learning environment"),
        ("What does PWU JASMS aspire to achieve through its vision statement?", "To dominate the education market", "To create global leaders and innovators", "To generate high financial returns", "To maintain a strict hierarchical structure", "To create global leaders and innovators"),
        ("How does PWU JASMS aim to fulfill its mission of nurturing learning?", "By focusing solely on theoretical education", "By providing a one-size-fits-all approach to teaching", "By offering a variety of educational programs and extracurricular activities", "By excluding students from decision-making processes", "By offering a variety of educational programs and extracurricular activities"),
        ("What values are likely to be emphasized in PWU JASMS's mission and vision?", "Individualism and competition", "Collaboration and community service", "Ruthlessness and profit maximization", "Secrecy and exclusivity", "Collaboration and community service"),
        ("In what way does PWU JASMS's vision set it apart from other educational institutions?", "By prioritizing conformity over innovation", "By focusing solely on academic achievements", "By promoting a global perspective and leadership skills", "By discouraging students from pursuing higher education", "By promoting a global perspective and leadership skills"),
        ("What is the purpose of a business plan?", "To secure funding", "To outline the goals and strategies of a business", "To attract customers", "All of the above", "All of the above"),
        ("What is branding?", "A type of advertising", "The process of creating a unique identity for a product or service", "A legal document", "A financial statement", "The process of creating a unique identity for a product or service"),
        ("What is the purpose of networking in entrepreneurship?", "To build relationships that can lead to opportunities or resources", "To outsource business tasks", "To promote products or services", "To recruit employees", "To build relationships that can lead to opportunities or resources"),
        ("What is the purpose of market research?", " To gather data on customer preferences and market trends", "To set prices for products or services", "To hire new employees", "To develop advertising campaigns", "To gather data on customer preferences and market trends"),
        ("Which of the following is NOT a stage in the product development process?", "Ideation", "Prototype", "Market saturation", "Testing", "Market saturation"),
        ("What is the term for the process of setting specific, measurable, achievable, relevant, and time-bound goals?", "Goal setting", "Objective planning", "Target establishment", "SMART goals", "SMART goals"),
        ("What is the term for the ability to control one's impulses and emotions?", "Emotional intelligence", "Self-regulation", "Self-awareness", "Resilience", "Self-regulation"),
        ("Which of the following is not a characteristic of a growth mindset?", "Embracing challenges", "Viewing failure as permanent", "Persisting in the face of setbacks", "Learning from criticism", "Viewing failure as permanent"),
        ("What is the term for the ability to bounce back from adversity?", "Resilience", "Optimism", "Adaptability", "Persistence", "Resilience"),

    ]

    questions_difficult = [
        ("How are you feeling today?", "Good", "Bad", "...", "I don't know", "I don't know"),
        ("What is the term for the process of reflecting on one's thoughts and emotions?", "Self-disclosure", "Self-awareness", "Self-actualization", "Self-regulation", "Self-awareness"),
        ("From which harbinger did Yelan steal their gift to the Tsaritsa which was supposed to be a 'coat'?", "Regrator", "Marionette", "Damselette", "The Jester", "Regrator"),
        ("To which character does the constellation 'Nyctereutes Minor' belong to?", "Sayu", "Heizou", "Xiao", "Yanfei", "Sayu"),
        ("The ultimate voice line 'A thousand faces in a thousand places... can you find the answer?' to who does it belong to?", "Sparkle", "Sushang", "Welt", "Sampo", "Sparkle"),
        ("who says the this 'Brace yourself, this is gonna hurt!'?", "Tartaglia", "Dehya", "Beidou", "Kaeya", "Tartaglia"),
        ("The ultimate voice line 'Rise, phoenix!' to who does it belong to?", "Sushang", "Clara", "Yanqing", "Qingque", "Sushang"),
        ("In which year did the Titanic sink?", "1910", "1912", "1915", "1920", "1912"),
        ("What is the rarest blood type among humans?", "A+", "B-", "AB-", "O-", "AB-"),
        ("What is the chemical formula for laughing gas?", "CO2", "NO", "N2O", "NH3", "N2O"),
        ("What component connects the computer to a network, allowing it to communicate with other computers and devices?", "CPU", "GPU", "NIC (Network Interface Card)", "RAM", "NIC (Network Interface Card)"),
        ("What is the primary function of a graphics processing unit (GPU)?", "Processing data", "Displaying images on the screen", "Providing power to components", "Storing data permanently", "Displaying images on the screen"),
        ("Which component is responsible for managing the input and output of data in a computer system?", "CPU", "GPU", "I/O Controller", "RAM", "I/O Controller"),
        ("What component is used to cool down the CPU and prevent it from overheating?", "Heat sink", "RAM", "GPU", "Power supply unit", "Heat sink"),
        ("What component is responsible for managing the flow of data between the CPU and other components?", "Northbridge", "Southbridge", "RAM", "GPU", "Northbridge"),
        ("What does BIOS stand for?", "Basic Input/Output System", "Basic Integrated Operating System", "Binary Input/Output System", "Backup Input/Output System", "Basic Input/Output System"),
        ("What is the function of a CPU cache?", "Provides temporary storage for the operating system", "Manages communication between components", "Stores frequently accessed data for quick access by the CPU", "Displays images on the screen", "Stores frequently accessed data for quick access by the CPU"),
        ("What type of storage device has no moving parts and provides faster access to data compared to traditional hard disk drives (HDDs)?", "HDD", "SSD", "RAM", "CPU", "SSD"),
        ("What is the purpose of a network switch?", "Connects computers to a wireless network", "Connects computers to a wired network", "Connects multiple networks together", "Boosts the speed of internet connections", "Connects computers to a wired network"),
        ("Which component is responsible for converting digital signals from the computer into analog signals for output to speakers or headphones?", "Sound card", "CPU", "RAM", "SSD", "Sound card"),
        ("What is the first step in the research process?", "Data analysis", "Conclusion", "Problem identification", "Literature review", "Problem identification"),
        ("Which of the following is NOT a common research methodology?", "Case study", "Experiment", "Survey", "Observation", "Experiment"),
        ("What is the purpose of a control group in an experiment?", "To receive the experimental treatment", "To provide a basis for comparison", "To ensure the experiment is ethical", "To gather qualitative data", "To provide a basis for comparison"),
        ("What is a literature review?", "A summary of the research findings", "A review of books unrelated to the research topic", "An overview of existing research on a topic", "A review of fictional literature", "An overview of existing research on a topic"),
        ("Which of the following is NOT a common type of research bias?", "Confirmation bias", "Sampling bias", "Measurement bias", "Peer review bias", "Peer review bias"),
        ("Which of the following is NOT a type of informative speech?", "Demonstrative", "Explanatory", "Persuasive", "Descriptive", "Persuasive"),
        ("What is the term for the process of sending a message to someone else?", "Encoding", "Decoding", "Feedback", "Feedback", "Encoding"),
        ("Which of the following is a characteristic of assertive communication?", "Aggressiveness", "Passivity", "Confidence", "Indecisiveness", "Confidence"),
        ("Which of the following is a characteristic of effective body language?", "Slouching", "Crossing arms", "Maintaining eye contact", "Avoiding gestures", "Maintaining eye contact"),
        ("What is the term for adjusting one's speech to fit the audience's preferences and expectations?", "Adaptation", "Synchronization", "Articulation", "Elaboration", "Adaptation"),
        ("Which of the following is NOT a part of active listening?", "Interrupting", "Nodding", "Clarifying", "Summarizing", "Interrupting"),
        ("Which of the following is a barrier to effective oral communication?", "Active listening", "Clarity", "Noise", "Eye contact", "Noise"),
        ("What is the primary purpose of oral communication?", "To confuse the audience", "To convey information", "To create barriers", "To exclude the audience", "To convey information"),
        ("What is the most effective way to deal with distractions during oral communication?", "Ignoring them", "Stopping the communication", "Acknowledging them and then continuing", "Raising your voice", "Acknowledging them and then continuing"),
        ("Which of the following is a benefit of effective oral communication in the workplace?", "Decreased productivity", "Improved teamwork", "Misunderstandings", "Higher turnover rates", "Improved teamwork"),
        ("Which of the following is NOT a primary element of poetry?", "Rhyme", "Meter", "Thesis statement", "Stanza", "Thesis statement"),
        ("Which of the following literary devices is used in the following sentence: 'The stars danced playfully in the moonlit sky'?", "Metaphor", "Simile", "Personification", "Hyperbole", "Personification"),
        ("Which of the following is NOT a form of non-fiction writing?", "Autobiography", "Novel", "Biography", "Essay", "Novel"),
        ("What is the definition of the term 'exposition' in literature?", "The final resolution of the plot", "The turning point in the story", "The introduction of characters and setting", "The climax of the story", "The introduction of characters and setting"),
        ("Which of the following literary devices is used in the following sentence: 'The stars danced playfully in the moonlit sky'?", "Metaphor", "Simile", "Personification", "Hyperbole", "Personification"),
        ("Who was the last Tsar of Russia?", "Nicholas II", "Peter the Great", "Ivan the Terrible", "Catherine the Great", "Nicholas II"),
        ("The 'Truman Doctrine' was a policy primarily aimed at containing the spread of what?", "Communism", "Capitalism", "Nationalism", "Fascism", "Communism"),
        ("The ancient city of Rome was founded in which year?", "753 BC", "476 AD", "1066 AD", "44 BC", "753 BC"),
        ("The fall of which city marked the end of the Byzantine Empire?", "Athens", "Rome", "Constantinople", "Alexandria", "Constantinople"),
        ("Who was the longest-reigning British monarch?", "Queen Elizabeth II", "Queen Victoria", "King George III", "King Henry VIII", "Queen Victoria"),
        ("What is the longest mountain range in the world?", "The Rockies", "The Andes", "The Himalayas", "The Alps", "The Andes"),
        ("Which of these is not one of the Great Lakes of North America?", "Lake Superior", "Lake Powell", "Lake Ontario", "Lake Michigan", "Lake Powell"),
        ("What is the capital of Spain?", "Madrid", "Barcelona", "Seville", "Valencia", "Madrid"),
        ("What is the world's longest river?", "Nile", "Amazon", "Yangtze", "Mississippi", "Nile"),
        ("Which of the following countries is completely landlocked?", "Romania", "Greece", "Hungary", "Luxembourg", "Hungary"),

    ]

    questions_boss1 = [
        ("What is the term for a low-lying area of land that is surrounded by higher land?", "Basin", "Plain", "Plateau", "Valley", "Basin"),
        ("What is the term for a large area of flat or gently rolling land?", "Plain", "Delta", "Plateau", "Valley", "Plain"),
        ("What is the definition of topography?", "The study of celestial bodies", "The study of the Earth's surface features", "The study of ocean currents", "The study of weather patterns", "The study of the Earth's surface features"),
        ("What is the term for a deep valley with steep sides, often with a river flowing through it?", "Peninsula", "Canyon", "Plateau", "Delta", "Canyon"),
        ("What is the term for a chain of islands?", "Peninsula", "Archipelago", "Isthmus", "Delta", "Archipelago"),
        ("Saturn is associated with what?", "Luck", "Authority and discipline", "Love", "Creativity", "Authority and discipline"),
        ("The zodiac sign of Cancer is represented by which creature?", "A lion", "A crab", "A fish", "A scorpion", "A crab"),
        ("How many zodiac signs are there?", "10", "12", "5", "7", "12"),
        ("What is astrology?", "The study of the movements and relative positions of celestial bodies", "The study of the Earth's geological features", "The study of the human brain", "The study of ancient artifacts", "The study of the movements and relative positions of celestial bodies"),
        ("Which planet is known as the 'planet of love' in astrology?", "Venus", "Mars", "Jupiter", "Saturn", "Venus"),
        ("What is the name of the process by which plants convert light energy into chemical energy?", "Photosynthesis", "Respiration", "Fermentation", "Transpiration", "Photosynthesis"),
        ("Which of the following is a method of soilless cultivation that uses a nutrient-rich water solvent?", "Hydroponics", "Aeroponics", "Aquaponics", "Vermiponics", "Hydroponics"),
        ("What is the primary function of fertilizer in agriculture?", "To increase soil acidity", "To kill pests and diseases", "To provide essential nutrients to plants", "To prevent soil erosion", "To provide essential nutrients to plants"),
        ("What is the term for the process of exposing food to controlled amounts of ionizing radiation to kill bacteria?", "Pasteurization", "Fermentation", "Irradiation", "Culturing", "Irradiation"),
        ("Which of the following is not a method of organic pest control?", "Biological control", "Crop rotation", "Chemical pesticides", "Use of natural predators", "Chemical pesticides"),
        ("Which composer is known for the opera 'The Barber of Seville'?", "Wolfgang Amadeus Mozart", "Giacomo Puccini", "Gioachino Rossini", "Giuseppe Verdi", "Gioachino Rossini"),
        ("The Baroque period falls roughly between:", "1600-1750", "1400-1600", "1750-1820", "1820-1900", "1600-1750"),
        ("Which composer is known as the 'Father of the Symphony'?", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Joseph Haydn", "Franz Schubert", "Joseph Haydn"),
        ("Who is known as the 'King of Ragtime'?", "Scott Joplin", "Louis Armstrong", "Duke Ellington", "Benny Goodman", "Scott Joplin"),
        ("Who composed 'Symphony No. 9'?", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Franz Schubert", "Gustav Mahler", "Ludwig van Beethoven"),
        ("In which country is Oktoberfest celebrated?", "Germany", "United States", "Austria", "Switzerland", "Germany"),
        ("Which holiday is known as the 'Festival of Lights'?", "Christmas", "Hanukkah", "Diwali", "Kwanzaa", "Diwali"),
        ("In which country is Bastille Day celebrated?", "France", "Germany", "Italy", "Spain", "France"),
        ("What is the most widely celebrated holiday in the world?", " Christmas", "New Year's Day", "Halloween", "Easter", "Christmas"),
        ("What is the traditional color associated with St. Patrick's Day?", "Red", "Blue", "Green", "Yellow", "Green"),
        ("What is the name of the end of the world in Norse mythology?", "Ragnarok", "Armageddon", "Doomsday", "The Final Battle", "Ragnarok"),
        ("Who is the father of Fenrir, Jörmungandr, and Hel in Norse mythology?", "Loki", "Thor", "Odin", "Tyr", "Loki"),
        ("Who is the god of winter in Norse mythology?", "Freyr", "Ullr", "Njord", "Skadi", "Ullr"),
        ("Who is the god of dawn in Norse mythology?", "Dagur", "Ullr", "Vidar", "Mani", "Dagur"),
        ("Who is the Greek god of the forge?", "Hephaestus", "Hermes", "Apollo", "Ares", "Hephaestus"),
        ("Who was the first female President of Brazil?", "Dilma Rousseff", "Luiz Inácio Lula da Silva", "Jair Bolsonaro", "Michel Temer", "Dilma Rousseff"),
        ("Who was the first President of the French Fifth Republic?", "Charles de Gaulle", "François Mitterrand", "Jacques Chirac", "Nicolas Sarkozy", "Charles de Gaulle"),
        ("Who was the first Chancellor of Germany after the reunification of East and West Germany?", "Helmut Kohl", "Konrad Adenauer", "Willy Brandt", "Angela Merkel", "Helmut Kohl"),
        ("Who was the longest-serving Prime Minister of the United Kingdom in the 20th century?", "Margaret Thatcher", "Winston Churchill", "Tony Blair", "David Lloyd George", "Margaret Thatcher"),
        ("Who was the first President of the United States to be impeached?", "Richard Nixon", "Andrew Johnson", "Donald Trump", "Bill Clinton", "Andrew Johnson"),
        ("Who is often credited with being the 'Father of Modern Olympics'?", "Pierre de Coubertin", "Avery Brundage", "James E. Sullivan", "Juan Antonio Samaranch", "Pierre de Coubertin"),
        ("In what year did the first modern marathon race take place?", "1896", "1904", "1908", "1912", "1896"),
        ("Golf is said to have originated in:", "Scotland", "England", "Ireland", "France", "Scotland"),
        ("The term 'Grand Slam' in tennis refers to:", "Winning all four major tournaments in a calendar year", "Winning the French Open and Wimbledon in the same year", "Winning all four Grand Slam events over a career", "Winning the US Open and Australian Open in the same year", "Winning all four Grand Slam events over a career"),
        ("Who is often credited with the invention of the game of volleyball?", "William G. Morgan", "James Naismith", "Albert Spalding", "Morgan Stanley", "William G. Morgan"),
        ("How many Battlesuits does valkyrie 'Seele Vollerei'have?", "13", "4", "7", "5", "4"),
        ("How many Herrschers were present in 'Honkai Impact 3rd' in the previous era?", "13", "9", "27", "14", "13"),
        ("What is the name of the dragon that serves the 'Herrscher of the Void'?", "Benares", "Kurikara", "Vishmu", "Padishah", "Benares"),
        ("In which form can Furina heal in?", "Pneuma", "Ouisia", "Kokomi", "Barbara", "Pneuma"),
        ("In 'Terraria: Calamity' what is the name of the supreme witch", "Calamitas", "Erinas", "Knuera", "Symfora", "Calamitas"),
        ("Which CSS property is used to control the text size of an element?", "text-size", "font-size", "text-style", "font-style", "font-size"),
        ("Which of the following is NOT a valid method for creating an HTML form button?", "<button>", "<input type='submit'>", "<input type='button'>", "<button type='button'>", "<button type='button'>"),
        ("What does the 'SQL' stand for in web development?", "Structured Query Language", "Simple Query Language", "Structured Question Language", "Simple Question Language", "Structured Query Language"),
        ("Which of the following CSS properties is used to change the color of text?", "text-color", "color", "font-color", "text-style", "color"),
        ("Which HTML tag is used to define an unordered list?", "<ol>", "<dl>", "<list>", "<ul>", "<ul>"),
    ]

    questions_final_battle = [
        ("What does API stand for?", "Application Programming Interface", "Advanced Programming Interface", "Application Process Interface", "Advanced Process Interface", "Application Programming Interface"),
        ("What is the purpose of the 'elif' statement in Python?", "To terminate the program", "To catch exceptions", "To execute a block of code if the first condition is false", "To check another condition if the previous condition is false", "To check another condition if the previous condition is false"),
        ("Which of the following is not a valid data type in Python?", "String", "Float", "Boolean", "Character", "Character"),
        ("What is the purpose of the 'pass' statement in Python?", "To terminate the program", "To catch exceptions", "To execute a block of code if the condition is false", "To do nothing", "To do nothing"),
        ("What is the purpose of a comment in programming?", "To store data", "To terminate the program", "To make the code more readable and understandable", "To declare variables", "To make the code more readable and understandable"),
        ("If the price of a substitute good increases, what happens to the demand for the original good?", "The demand for the original good decreases", "The demand for the original good increases", "The supply of the original good increases", "There is no change in the demand for the original good", "The demand for the original good increases"),
        ("What is the result of a price floor set above the equilibrium price?", "A shortage", "A surplus", "No change in the market", "An increase in equilibrium price", "A surplus"),
        ("What happens to the equilibrium price and quantity when both demand and supply increase?", "Equilibrium price remains the same, and quantity increases", "Equilibrium price and quantity both increase", "Equilibrium price and quantity both decrease", "Equilibrium price increases, and quantity decreases", "Equilibrium price remains the same, and quantity increases"),
        ("What is the law of demand?", "As the price of a good increases, the quantity demanded increases", "As the price of a good decreases, the quantity demanded increases", "As the price of a good decreases, the quantity demanded decreases", "As the price of a good decreases, the quantity demanded decreases", "As the price of a good increases, the quantity demanded decreases"),
        ("What is the law of supply?", "As the price of a good increases, the quantity supplied increases", "As the price of a good decreases, the quantity supplied increases", "As the price of a good increases, the quantity supplied decreases", "As the price of a good decreases, the quantity supplied decreases", "As the price of a good increases, the quantity supplied increases"),
        ("Which of the following is a fretted string instrument with a pear-shaped body and four strings?", "Violin", "Cello", "Viola", "Ukulele", "Ukulele"),
        ("Which instrument belongs to the brass family?", "Flute", "Guitar", "Trumpet", "Violin", "Trumpet"),
        ("Which instrument is used to set the rhythm of a musical piece?", "Piano", "Drum", "Violin", "Flute", "Drum"),
        ("The instrument with the widest range in the orchestra is the?", "Violin", "Cello", "Piano", "French Horn", "Piano"),
        ("Which instrument has foot pedals to change the pitch of the strings?", "Violin", "Harp", "Guitar", "Drum", "Harp"),
        ("What does the term 'composition' refer to in art?", "The surface quality of an object", "The path of a moving point", "The way the elements are arranged and composed in a work of art", "The three-dimensional aspect of an object", "The way the elements are arranged and composed in a work of art"),
        ("Which element of art refers to the use of light and dark, shade and highlight, in an artwork?", "Color", "Line", "Value", "Shape", "Value"),
        ("What is the term used to describe the purity or intensity of a color?", "Saturation", "Hue", "Value", "Intensity", "Saturation"),
        ("What is the main purpose of color in art?", "To create movement", "To define form", "To evoke emotions and set a mood", "To enclose space", "To evoke emotions and set a mood"),
        ("Which element of art is defined as a two-dimensional area with identifiable boundaries?", "Color", "Line", "Texture", "Shape", "Shape"),
        ("The term 'Cradle of Civilization' refers to which ancient region?", "Nile River Valley", "Indus River Valley", "Mesopotamia", "Yellow River Valley", "Mesopotamia"),
        ("The ancient city of Carthage was located in modern-day:", "Italy", "Spain", "Tunisia", "Greece", "Tunisia"),
        ("The ancient city of Machu Picchu is located in which modern-day country?", "Brazil", "Peru", "Mexico", "Colombia", "Peru"),
        ("The ancient city of Pompeii was destroyed by the eruption of which volcano?", "Mount Etna", "Mount Vesuvius", "Mount St. Helens", "Mount Kilimanjaro", "Mount Vesuvius"),
        ("Which ancient civilization built the Parthenon?", "Egypt", "Greece", "Rome", "Persia", "Greece"),
        ("What is the primary focus of an argumentative essay?", "To tell a story", "To inform", "To persuade", "To describe", "To persuade"),
        ("What is the purpose of a hook in the introduction of an essay?", "To provide evidence", "To grab the reader's attention", "To introduce the thesis", "To summarize the main points", "To grab the reader's attention"),
        ("What does the term 'cohesion' refer to in essay writing?", "The use of appropriate vocabulary", "The flow and connectivity of ideas", "The length of the essay", "The number of paragraphs", "The flow and connectivity of ideas"),
        ("What is the purpose of a counter-argument in an essay?", "To strengthen the main argument", "To provide additional evidence", "To weaken the main argument", "To confuse the reader", "To strengthen the main argument"),
        ("What is the appropriate tense to use when writing an essay?", "Past tense", "Present tense", "Future tense", "Both past and present tense", "Present tense"),
        ("What part of speech is the word 'blue' in the following sentence? The sky is 'blue'.", "Adverb", "Noun", "Verb", "Adjective", "Adjective"),
        ("What part of speech is the word 'interesting' in the following sentence? The book is 'interesting'.", "Adjective", "Noun", "Verb", "Adverb", "Adjective"),
        ("What part of speech is the word 'angrily' in the following sentence? She spoke 'angrily' to her boss.", "Adjective", "Adverb", "Verb", "Noun", "Adverb"),
        ("What part of speech is the word 'dog' in the following sentence? His 'dog' is very friendly.", "Noun", "Verb", "Adjective", "Adverb", "Noun"),
        ("What part of speech is the word 'cry' in the following sentence? She began to cry after watching the sad movie.", "Verb", "Adjective", "Adverb", "Noun", "Verb"),
        ("Newton's First Law of Motion states that an object will remain at rest or in uniform motion in a straight line unless acted upon by an external force. This is also known as the law of:", "Inertia", "Momentum", "Action", "Acceleration", "Inertia"),
        ("Which of the following scenarios represents the Second Law of Motion?", "A baseball accelerating after being hit by a bat", "A person standing still on the ground", "A car moving at a constant speed on a straight road", "A spacecraft in the vacuum of space", "A baseball accelerating after being hit by a bat"),
        ("If the mass of an object is doubled, what happens to the force needed to produce the same acceleration?", "It is halved", "It is doubled", "It is tripled", "It remains the same", "It is halved"),
        ("What is the SI unit of force?", "Newton (N)", "Kilogram (kg)", "Meter per second squared (m/s^2)", "Pascal (Pa)", "Newton (N)"),
        ("According to Newton's First Law of Motion, an object will continue to do what unless acted upon by an unbalanced force?", "Accelerate", "Move at a constant velocity", "Move in a straight line", "Change direction", "Move at a constant velocity"),
        ("What is the perimeter of a square with a side length of 8 cm?", "24 cm", "32 cm", "40 cm", "64 cm", "32 cm"),
        ("What is the measure of each interior angle of a regular pentagon?", "72°", "108°", "120°", "144°", "108°"),
        ("What is the perimeter of a triangle with side lengths 5 cm, 6 cm, and 7 cm?", "15 cm", "18 cm", "20 cm", "24 cm", "18 cm"),
        ("What is 75% written as a decimal?", "0.0075", "0.75", "0.075", "7.5", "0.75"),
        ("What is 2/3 as a percentage?", "25%", "66.67%", "50%", "75%", "66.67%"),
        ("Out of the thirteen Flame-Chasers, who is 'XI - Infinity'?", "Mobius", "Eden", "Griseo", "Aponia", "Mobius"),
        ("To who does constellation 'Victor Mare' belong to?", "Beidou", "Tartaglia", "Dehya", "Chongyun", "Beidou"),
        ("To who does constellation 'Noctuna' belong to?", "Diluc", "Mona", "Fischl", "Klee", "Diluc"),
        ("To who does constellation 'Felis Alba' belong to?", "Diona", "Kirara", "Lynette", "Keqing", "Lynette"),
        ("In the gacha game Nikke: Goddess of Victory, some members of the Goddess squad are based on what?", "Grimm Fairy Tales", "Mythology", "The Bible", "Folktales", "Grimm Fairy Tales"),
    ]