init python:
    positive_feedback = [
        "That's correct!",
        "Exactly right!",
        "Spot on!",
        "Well said!",
        "You nailed it!",
        "That's the way!",
        "I agree!",
        "You're absolutely right!",
        "That's it!",
        "I'm with you on that!",
        "Great point!",
        "You're on the mark!",
        "Couldn't agree more!",
        "Well done!",
        "Exactly!",
        "That's the ticket!",
        "You're spot on!",
        "Precisely!",
        "Perfect!",
        "Couldn't have said it better!"
    ]
    negative_feedback = [
        "Hmm, not quite.",
        "I'm not so sure about that.",
        "Hmm, that's interesting.",
        "I see what you mean.",
        "Hmm, maybe.",
        "That's not quite it.",
        "I think so?",
        "That's a perspective.",
        "Interesting.",
        "Hmm, not sure.",
        "Let me think about that.",
        "Hmm, that's something to consider.",
        "Could be, I suppose.",
        "Hmm, I see.",
        "That's one way to look at it.",
        "Interesting thought.",
        "Hmm, I'll think on it.",
        "That's an interesting take.",
        "It's possible, I guess.",
        "Interesting point."
    ]
